# Jekyll Resume Theme

# Site settings
title: Philipe Godoy
email: mbx.philipe@gmail.com
description: Web developer
baseurl: ""
url: "http://josenberg.com"
name: Philipe Godoy
job: Web developer
location: Campinas, Brasil
languages: HTML, CSS and Javascript
email_address: mbx.philipe@gmail.com

# Build settings
markdown: kramdown
